@host = {{$dotenv API_URL}}
@token={{$dotenv BEARER_TOKEN}}

### @name customers
GET {{host}}/api/customers HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### @name customers/1
GET {{host}}/api/customers/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}